export default [
  {
    path: '/user',
    layout: false,
    routes: [
      { path: 'login', component: './User/Login' },
      { path: '', redirect: '/user/login' }, // 重定向到登录页面
    ],
  },
  {
    path: '/airConditioning',
    name: '114_空调水机主机',
    icon: 'thunderbolt',
    component: './AirConditioning',
    access: 'canUser',
  },
  {
    path: '/injection_workshop',
    name: '110注射环保设备',
    icon: 'experiment',
    component: './InjectionWorkshop',
    access: 'canUser',
  },
  {
    path: '/granulation_workshop',
    name: '102造粒环保设备',
    icon: 'build',
    component: './GranulationWorkshop',
    access: 'canUser',
  },
  {
    path: '/office_building',
    name: '1#办公楼',
    icon: 'home',
    component: './OfficeBuilding',
    access: 'canUser',
  },

  {
    path: '/feeding_workshop',
    name: '101配料',
    icon: 'container',
    component: './FeedingWorkshop',
    access: 'canUser',
  },
  {
    path: '/granule102',
    name: '102造粒',
    icon: 'build',
    component: './Granule102',
    access: 'canUser',
  },
  {
    path: '/cold-press-103',
    name: '103冷压',
    icon: 'GatewayOutlined',
    component: './ColdPress103',
    access: 'canUser',
  },
  {
    path: '/restoration-104',
    name: '104还原',
    icon: 'BgColorsOutlined',
    component: './Restoration104',
    access: 'canUser',
  },
  {
    path: '/sintering-105',
    name: '105烧结',
    component: './Sintering105',
    icon: 'fire', //
    access: 'canUser',
  },
  {
    path: '/cleaning-106',
    name: '106清洗',
    component: './Cleaning106',
    icon: 'interaction',
    access: 'canUser',
  },
  {
    path: '/beading-107',
    name: '107串珠',
    component: './Beading107',
    icon: 'link',
    access: 'canUser',
  },
  {
    path: '/rubber-109',
    name: '109炼胶',
    component: './Rubber109',
    icon: 'experiment',
    access: 'canUser',
  },
  {
    path: '/injection-110',
    name: '110注射',
    component: './Injection110',
    icon: 'control',
    access: 'canUser',
  },
  {
    path: '/edging-111',
    name: '111开刃',
    component: './Edging111',
    icon: 'scissor',
    access: 'canUser',
  },
  {
    path: '/final-inspection-112',
    name: '112终检',
    component: './FinalInspection112',
    icon: 'ToolFilled',
    access: 'canUser',
  },
  {
    path: '/admin',
    icon: 'crown',
    name: '管理页',
    access: 'canAdmin',
    routes: [
      { path: '', redirect: 'user' },
      { icon: 'table', path: 'user', component: './Admin/User', name: '用户管理' },
    ],
  },
  { path: '/', redirect: '/airConditioning'},
  { path: '*', layout: false, component: './404' },
];
